language: java
jdk: oraclejdk8
install:
  - ./gradlew -info
  - ./gradlew setupCIWorkspace --stacktrace
script: ./gradlew build --stacktrace
branches:
  only:
  - master
before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""